/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package it.unibo.ise.lab.resolution

import kotlin.test.Test
import kotlin.test.assertTrue

class LibraryTest {
    @Test fun someLibraryMethodReturnsTrue() {
        val classUnderTest = PrologLike()
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'")
    }
}
